import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.scss"

import localFont from "next/font/local"

const norse = localFont({
  src: [
    {
      path: "../../public/fonts/Norse.otf"
    }
    // {
    //   path: "../../public/fonts/Poppins-Bold.ttf",
    //   weight: "700"
    // }
  ],
  variable: "--font-norse"
})

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${norse.variable} font-sans`}>{children}</body>
    </html>
  )
}
